### ISSUE TITLE
Could you please provide the experimental parameter configuration of other datasets？

### ISSUE THREAD

**Issue by kolincc** [jlu-phyComputer/T2B-PE#1]

**Comment by jlu-phyComputer** [comment]
Thank you for your attention！The article is currently under review. Once the article is accepted, we will be happy to provide the experimental parameter configuration of other datasets.

**Comment by jlu-phyComputer** [comment]
Thank you for your attention! The article is currently under review. Once the article is accepted, we will be happy to provide the training script (sh file) of other datasets.

**Comment by kolincc** [comment]
Thx ：）

**Comment by kolincc** [comment]
Thx : )
