### ISSUE TITLE
您好？

### ISSUE THREAD

**Issue by yejunjiePDH** [jlu-phyComputer/T2B-PE#2]
作者您好，看了您的论文写的非常棒，但是文中学习率调的比较奇怪，ETTh2的结果是异常的优越，划分比例是否是6：2：2。能否提供一下具体脚本文件，非常感谢。

**Comment by jlu-phyComputer** [comment]
感谢关注，文章目前正在审核中。一旦文章被接受，我们将很乐意提供其他数据集的训练脚本（sh 文件）。

**Comment by jlu-phyComputer** [comment]
学习率比较奇怪是因为我们进行了学习率搜素
